# Generated by Django 4.1.3 on 2022-11-14 18:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name of budget')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Budget balance')),
                ('date_create', models.DateTimeField(default=datetime.datetime(2022, 11, 14, 21, 32, 7, 773674), verbose_name='Time of create')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Time of update')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Account')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Category name')),
                ('description', models.TextField(verbose_name='Description of category')),
                ('date_create', models.DateTimeField(default=datetime.datetime(2022, 11, 14, 21, 32, 7, 773674), verbose_name='Time of create')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Time of update')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Tag name')),
                ('date_create', models.DateTimeField(default=datetime.datetime(2022, 11, 14, 21, 32, 7, 773674), verbose_name='Time of create')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Time of update')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount money')),
                ('date_create', models.DateTimeField(default=datetime.datetime(2022, 11, 14, 21, 32, 7, 773674), verbose_name='Time of create')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='accounts.account', verbose_name='From account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='accounts.account', verbose_name='To account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount money')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 11, 14, 21, 32, 7, 773674), verbose_name='Time of create')),
                ('description', models.TextField(verbose_name='Description')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Time of update')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Account')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.budget', verbose_name='Budget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.category', verbose_name='Category')),
                ('tag', models.ManyToManyField(to='manager.tag')),
            ],
        ),
    ]
