# Generated by Django 4.1.3 on 2022-11-15 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_budget_date_create_alter_category_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='', max_length=75, verbose_name='Transaction type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 8, 55, 17, 351640), verbose_name='Time of create'),
        ),
        migrations.AlterField(
            model_name='category',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 8, 55, 17, 351640), verbose_name='Time of create'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 8, 55, 17, 351640), verbose_name='Time of create'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 8, 55, 17, 351640), verbose_name='Time of create'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 8, 55, 17, 351640), verbose_name='Time of create'),
        ),
    ]
