# Generated by Django 4.1.3 on 2022-11-15 07:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0004_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 10, 1, 37, 415010), verbose_name='Time of create'),
        ),
        migrations.AlterField(
            model_name='category',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 10, 1, 37, 415010), verbose_name='Time of create'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 10, 1, 37, 415010), verbose_name='Time of create'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 10, 1, 37, 415010), verbose_name='Time of create'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 10, 1, 37, 415010), verbose_name='Time of create'),
        ),
    ]
