# Generated by Django 4.1.3 on 2022-11-15 14:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_date_create'),
        ('manager', '0005_category_user_alter_budget_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 17, 4, 57, 597099), verbose_name='Time of create'),
        ),
        migrations.AlterField(
            model_name='category',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 17, 4, 57, 597099), verbose_name='Time of create'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 17, 4, 57, 597099), verbose_name='Time of create'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 17, 4, 57, 597099), verbose_name='Time of create'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 17, 4, 57, 597099), verbose_name='Time of create'),
        ),
    ]
