# Generated by Django 4.1.3 on 2022-11-14 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Account balance')),
                ('date_create', models.DateTimeField(default=datetime.datetime(2022, 11, 14, 21, 32, 7, 773674), verbose_name='Time of create')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Time of update')),
            ],
        ),
    ]
