# Generated by Django 4.1.3 on 2022-11-15 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 10, 1, 37, 383772), verbose_name='Time of create'),
        ),
    ]
