# Generated by Django 4.1.3 on 2022-11-15 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 17, 4, 57, 597099), verbose_name='Time of create'),
        ),
    ]
