# Generated by Django 4.1.3 on 2022-11-16 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 10, 25, 24, 785987), verbose_name='Time of create'),
        ),
    ]
